apiVersion: v1
kind: ConfigMap
metadata:
  name: db-info
data:
  DB_NAME: udagram
  DB_USER: postgres
  DB_HOST: a2d75b6844a4346d1870e08b4a5672d8-270586668.us-east-1.elb.amazonaws.com
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  ENCODED_PASSWORD: <OUTPUT OF `echo -n 'the password' | base64`>